psql.host=localhost
psql.port=5432
psql.dbname=regatta_tracker_db
psql.min_sessions=10
psql.max_sessions=10

redis.host = localhost
redis.port = 6379
redis.min_sessions = 10
redis.max_sessions = 10

rabbitmq.vhost=/